# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title FPOP2D 
#'                                                                                                        
#' @description Detecting changepoints using the functional pruning optimal partitioning method (fpop) in bivariate time series.                         
#'                                                                                                       
#' @param data1 is a vector of data1(a univariate time series).                                
#' @param data2 is a vector of data2(a univariate time series).                                
#' @param penalty is a value of penalty (a non-negative real number).                                        
#' @param type is a value defining the  type of pruning (0 = PELT, 1 = FPOP(intersection of sets), 2 = FPOP(intersection of set \ union of set ).       
#'                                                                                                          
#' @return a list of 4 elements  = (changepoints, means1, means2, globalCost).                    
#'  
#' \describe{
#' \item{\code{changepoints}}{is the vector of changepoints.}
#' \item{\code{means1}}{is the vector of successive means for data1.}
#' \item{\code{means2}}{is the vector of successive means for data2.}
#' \item{\code{globalCost}}{is a number equal to the global cost.}
#' }                                                                                                                                                                             #     
#'             
#' @examples FPOP2D (data1 = c(0,0,0,1,1,1), data2 = c(2,2,2,0,0,0), penalty = 2*log(6),  type = 1) 
FPOP2D <- function(data1, data2, penalty, type) {
    .Call(`_fpop2D_FPOP2D`, data1, data2, penalty, type)
}

