# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


FPOP2D <- function(data1, data2, penalty, type) {
    .Call(`_fpop2D_FPOP2D`, data1, data2, penalty, type)
}

